### ISSUE TITLE
Snapshot bug

### ISSUE THREAD

**Issue by Avantisankalp** [Avantisankalp/Troubleshooting#38]
From: bijeta@avantifellows.org<br>
Subject: Snapshot bug<br>
First Attachment: September 10, 2018 at 05:30AM https://ift.tt/2MXWibA<br>
Date: September 10, 2018 at 09:39AM<br>
<br>
Hi, I am unable to open my clobs. The screenshot shows the following error that pops up.<br>
<br>
Label:<br>
<br>
via Gmail

**Comment by Avantisankalp** [comment]
@bijetaavantifellows is this resolved now?

**Comment by bijetaavantifellows** [comment]
Hi Brinda,
This is not resolved, I think. My tablet is in AF office, if you are
visiting on friday can you have a look at the pending forms (clobs with
videos) too which are not getting submitted.

Thank you!

Bijeta

**Comment by Avantisankalp** [comment]
This was happening due to Video storage problem which is now resolved. @bijetaavantifellows Closing this issue.
